### ISSUE TITLE
Data Wizard Development

### ISSUE THREAD

**Issue by joshsager** [internetofwater/HubKit#1]
![Proposed-sensor-data-workflow_v2](https://user-images.githubusercontent.com/1139760/104593377-9c49ad00-563d-11eb-8209-a8ced076d461.png)

**Comment by ksonda** [comment]
I need to test this on my fresh setup

**Comment by ksonda** [comment]
We need to make sure this works operationally, and then write clear documentation for how to use.

**Comment by ksonda** [comment]
The first pass of this is done, though issues and improvements will continue to come up
